import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google'
import { Space_Grotesk } from 'next/font/google'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

// const spaceGrotesk = localFont({
//   src:"./fonts/SpaceGrotesk-VariableFont_wght.ttf",
//   weight: "300 700", // Choose what you need
//   variable: '--font-space-grotesk',
// })

export const metadata: Metadata = {
  title: "ACE College of Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
